# fly.toml app configuration file generated for learn4cash on 2025-08-21T18:45:52-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'learn4cash'
primary_region = 'lhr'

[build]
  builder = 'paketobuildpacks/builder:base'

[env]
  PORT = '8080'

