[project]
name = "python-template"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
requires-python = ">=3.11"
dependencies = [
    "google-auth>=2.40.3",
    "gspread>=6.2.1",
    "oauth2client>=4.1.3",
    "pytelegrambotapi>=4.28.0",
    "schedule>=1.2.0",
]
